#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2025 tfoerst3r
# SPDX-License-Identifier: MIT

# Name        : rsyncNAS
# Version     : 0.1.0
# Description : Syncing resources with a NAS
# Required    : -
# Note        : -

#==========#
#== INIT ==#
#==========#
LOG=$0.log
RSYNC="/usr/bin/rsync"

CONF_BASE="\
-a \
--verbose \
--no-perms \
--no-owner \
--no-group \
--progress \
--delete-after \
--recursive \
--acls \
--xattrs \
--omit-dir-times"
#--chmod=D755,F644 \

SOURCES=(
"$HOME/"
"$HOME/education/"
"$HOME/development/"
)

TARGETS=(
"/mnt/nas/sync/tleptop/"
"/mnt/nas/education/"
"/mnt/nas/development/"
)

# Issue: elements which contain a space are not correctly concatenated!
CONFS=(
# leptop
""

# education
""

# development
""
)

#================#
#== USER INPUT ==#
#================#

#===============#
#== FUNCTIONS ==#
#===============#

#--- Set Variables ---#
function set_variables {
index_length=${#SOURCES[@]}
}

#-----Tests-----#

function test_length_array {
  local slen=${#SOURCES[@]}
  local tlen=${#TARGETS[@]}
  local clen=${#CONFS[@]}

  if (( slen != tlen || slen != clen )); then
    echo "Error: Array lengths do not match!" >&2
    exit 1
  fi
}

function test_mountpoints {
for (( i=0; i<index_length; i++ )); do
    if [[ ! -d "${TARGETS[i]}" ]]; then
        echo "Folder ${TARGETS[i]} is not mounted! SOURCES(${slen}), TARGETS(${tlen}), CONFS(${clen})" >&2
        exit 1
    fi
done
}

function test_all {
  test_length_array
  test_mountpoints
}

#--- Main Function ---#

function main {

echo "-------------------"
echo "Starting syncing..."
echo "-------------------"

for (( i=0; i<index_length; i++ )); do
  
  #TODO: options with spaces are not correctly parsed; issue with --filter! 
  
  echo "$RSYNC $CONF_BASE --filter=\"merge ${SOURCES[i]}.rsync-filter\" --exclude='$LOG' ${SOURCES[i]} ${TARGETS[i]} > $LOG$i"
  $RSYNC \
      $CONF_BASE --filter="merge ${SOURCES[i]}.rsync-filter" --exclude='$LOG' \
      ${SOURCES[i]} \
      ${TARGETS[i]} > "$LOG$i"

  echo "------------------------------------------"
  echo "...Done syncing ${SOURCES[i]}"
  echo "------------------------------------------"

done

}

#==========#
#== MAIN ==#
#==========#
set_variables
test_all
main

